### ISSUE TITLE
Can you provide more details about how data are stored?

### ISSUE THREAD

**Issue by MathLens** [alexklwong/void-dataset#1]
- The unit of depth in sparse and ground truth depth images?
- What do the validity map refer to?
- How are the poses stored? What's the reference frame?
- Intrinsics possibly vary among different sequences?

Thank you

**Comment by alexklwong** [comment]
Sparse depth and ground truth are both stored in meters

Validity map refers to the pixel locations where sparse depth is available

Absolute poses are stored at text files and are current timestamped (timestamp.txt inside 
 pose directories) camera to world. You can load them as numpy arrays using np.loadtxt(...) 

Intrinsics are provided as K.txt at each sequence directory and may vary a bit since we calibrate each time.

**Comment by MathLens** [comment]
Thanks for your reply.
But I think depths are not in meters, since most numbers are around 1000. Do you actually mean millimeters?

Also, can I simply get the available sparse depths by (Sparse depth > 0) instead of validity map?

**Comment by alexklwong** [comment]
Sorry I meant to type millimeters. Yes, you can get validity map that way as well.

**Comment by MathLens** [comment]
Thanks for your clarification!
